# Generated by Django 4.2.13 on 2024-06-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MesaAyuda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='casCodigo',
            field=models.CharField(db_comment='Codigo del caso', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userTipo',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Instructor', 'Instructor'), ('Tecnico', 'Tecnico')], db_comment='Tipo usuario', max_length=15),
        ),
    ]
